"""add lastfm profile and taste profile tables

Revision ID: 48724afaf4c2
Revises: 35acad4283a0
Create Date: 2026-04-12 19:03:53.156500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48724afaf4c2'
down_revision: Union[str, Sequence[str], None] = '35acad4283a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lastfm_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lastfm_username', sa.String(length=255), nullable=False),
    sa.Column('session_key', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('taste_profile_albums',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('album_name', sa.String(length=512), nullable=False),
    sa.Column('album_mbid', sa.Uuid(), nullable=True),
    sa.Column('artist_name', sa.String(length=512), nullable=False),
    sa.Column('artist_mbid', sa.Uuid(), nullable=True),
    sa.Column('playcount', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'period', 'album_name', 'artist_name')
    )
    op.create_index(op.f('ix_taste_profile_albums_user_id'), 'taste_profile_albums', ['user_id'], unique=False)
    op.create_table('taste_profile_artists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('artist_name', sa.String(length=512), nullable=False),
    sa.Column('artist_mbid', sa.Uuid(), nullable=True),
    sa.Column('playcount', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'period', 'artist_name')
    )
    op.create_index(op.f('ix_taste_profile_artists_user_id'), 'taste_profile_artists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taste_profile_artists_user_id'), table_name='taste_profile_artists')
    op.drop_table('taste_profile_artists')
    op.drop_index(op.f('ix_taste_profile_albums_user_id'), table_name='taste_profile_albums')
    op.drop_table('taste_profile_albums')
    op.drop_table('lastfm_profiles')
    # ### end Alembic commands ###
