"""'rename playcount to count and add discogs_profiles'

Revision ID: 5820d3435290
Revises: b2a5b7b5ba69
Create Date: 2026-04-18 20:49:32.992472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5820d3435290'
down_revision: Union[str, Sequence[str], None] = 'b2a5b7b5ba69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discogs_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('discogs_username', sa.String(length=255), nullable=True),
    sa.Column('request_token', sa.String(length=255), nullable=True),
    sa.Column('request_token_secret', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('access_token_secret', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('taste_profile_albums', 'playcount', new_column_name='count')
    op.alter_column('taste_profile_artists', 'playcount', new_column_name='count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discogs_profiles')
    op.alter_column('taste_profile_artists', 'count', new_column_name='playcount')
    op.alter_column('taste_profile_albums', 'count', new_column_name='playcount')
    # ### end Alembic commands ###
