"""add recommendation history table

Revision ID: a8f7cd795666
Revises: fc62dbcac6a8
Create Date: 2026-04-12 22:38:49.858230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f7cd795666'
down_revision: Union[str, Sequence[str], None] = 'fc62dbcac6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('artist_name', sa.String(length=512), nullable=False),
    sa.Column('artist_mbid', sa.Uuid(), nullable=True),
    sa.Column('seed_artist_name', sa.String(length=512), nullable=False),
    sa.Column('seed_artist_mbid', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recommendation_type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_history_user_id'), 'recommendation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_history_user_id'), table_name='recommendation_history')
    op.drop_table('recommendation_history')
    # ### end Alembic commands ###
