"""add artist listener cache table

Revision ID: b2a5b7b5ba69
Revises: a8f7cd795666
Create Date: 2026-04-13 00:47:34.265453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a5b7b5ba69'
down_revision: Union[str, Sequence[str], None] = 'a8f7cd795666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_listener_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artist_name', sa.String(length=512), nullable=False),
    sa.Column('listeners', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_listener_cache_artist_name'), 'artist_listener_cache', ['artist_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_listener_cache_artist_name'), table_name='artist_listener_cache')
    op.drop_table('artist_listener_cache')
    # ### end Alembic commands ###
